### ISSUE TITLE
Keep IR in sync between UI and Electron backend

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics-recorder#1]
+ Code currently works with the Playwright Actions IR and the backend and frontend has the logic of knowing when to convert the IR in to meaningful steps. This logic is spread in two places 
   - On the Synthetics formatter which formats the actions -> Synthetics step code -> https://github.com/elastic/synthetics-recorder/blob/e94611a4653cb473b8e1e7ab25efd6f042442b25/electron/formatter/synthetics.js#L24
   - On the UI during recording which generates the codes based on the actions recorded by the user -> https://github.com/elastic/synthetics-recorder/blob/e94611a4653cb473b8e1e7ab25efd6f042442b25/src/helpers/generator.js#L14

Before going live, we need to keep the IR consistent and keep a single source of truth so we could start supporting them in the Synthetics CLI.

**Comment by justinkambic** [comment]
@vigneshshanmugam given that we treat the Playwright IR as immutable and don't allow changes until after the recording session has ended at the moment, can we close this issue now?
