### ISSUE TITLE
feat: Update header to match new design

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#106]
We have a new design for the recorder's header:

![image](https://user-images.githubusercontent.com/18429259/144629482-0ff97569-53ac-490e-80d1-e613bb76f410.png)

Update the UI to reflect this. It will ensure we don't have any buttons hidden at the bottom of the UI, and make the body of the recorder less cluttered in general.

**Comment by awahab07** [comment]
**Post FF Testing:**
The header UI and functionality LGTM
- UI matches the design image.
- **Resume**, **Replay steps**, **View code** and **Export script** buttons work as expected.
- "Recording" and "Recording paused" statuses show correctly.

_Note_: Improvements are needed in UI below the header (not in the scope of this issue) e.g. the URL input field doesn't have a left margin.
<img width="1792" alt="Screenshot 2022-01-10 at 14 35 17" src="https://user-images.githubusercontent.com/2748376/148777806-399a31e3-96f1-44c6-8460-e859a6fe5285.png">
