### ISSUE TITLE
[Testing Infrastructure] There's a local web application available in our E2E tests for us to record journeys against

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#112]
To facilitate recording tests under a controlled environment during E2E tests, our E2E test setup should spin-up a web-application instance. This web application should be, preferably, the e-commerce application we use to demo our synthetics journeys.

Using such a web application allows us not to depend on third-parties for our tests to pass.

**Comment by paulb-elastic** [comment]
I'll let others in @elastic/uptime and @elastic/observablt-robots comment, but hasn't the https://github.com/spring-projects/spring-petclinic.git app has been used in the past?

**Comment by andrewvc** [comment]
Pet clinic I think has more deps so is harder to work with IIRC. 

@lucasfcosta is the TODOs app too simple? I like that there are so few moving pieces, but that's also its weakness.

**Comment by v1v** [comment]
What about the opbeans app? 
- https://github.com/elastic/opbeans-frontend

The APM ITs provide integration too with the opbeans app:
- https://github.com/elastic/apm-integration-testing/#opbeans

**Comment by lucasfcosta** [comment]
Very good points! I thought that the `TODOs` app would be enough for now because it has an input field, changes as we submit the form and also handles keyboard events (pressing `ENTER` to submit a `TODO`).

My main concern is avoiding tooling which requires too much setup so that tests remain easy to debug, but all demo applications you mentioned seem okay, although I have a slight preference for Node.js ones just so that maintainers can read the app's code and update it if necessary.

I can definitely see value in using something a bit more elaborate like the `opbeans-frontend` or the `sprint-petclinic` app though.

Does anyone have strong preferences? If not I'll have a look at `opbeans-frontend` and see how it compares to the TODO app.

**Comment by vigneshshanmugam** [comment]
IMO `opbeans-frontend` is a no no, It has too many deps and hasn't been updated like forever. I would just go with TODO app, if required we can bring the synthetics e-commerce demo as a SPA and has multiple pages.
