### ISSUE TITLE
[E2E Testing] Write tests for the main user journeys within the recorder

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#113]
We should write tests for the main user journeys within the script recorder.

These tests should include:

- [ ] Verifying steps when
    - [x] Navigating between pages
    - [ ] Filling and interacting with form inputs
- [ ] Pausing/continuing recordings
- [x] Adding different assertions
- [ ] Recording a test and re-running it
- [x] Editing steps https://github.com/elastic/synthetics-recorder/pull/175
- [ ] Removing steps
- [x] Validating a few different types of generated scripts which interface with form elements https://github.com/elastic/synthetics-recorder/pull/175
- [ ] Exporting scripts

**Comment by justinkambic** [comment]
Skipping Post-FF testing as these e2e tests run for each PR and we haven't had issues.
