### ISSUE TITLE
Sign windows binaries

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics-recorder#117]
Running the app, today, warns that it is unsigned. We should look into signing the binaries properly for releases.

**Comment by justinkambic** [comment]
Related to https://github.com/elastic/synthetics-recorder/issues/51.

**Comment by paulb-elastic** [comment]
Linking https://github.com/elastic/observability-robots/issues/1218

**Comment by kyungeunni** [comment]
Singed Windows binary is released: [v0.0.1-beta.3](https://github.com/elastic/synthetics-recorder/releases/tag/v0.0.1-beta.3)
