### ISSUE TITLE
[Enhancement] Preventing users from starting a journey without an initial URL

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#126]
### Feature summary

The users should not be able to start recording a journey without an URL, otherwise, we'll record a step in which they're taken to Chromium's `about:blank` page.

We should only enable the record button after the user enters a `URL` into the recorder's URL `input`.

### Why is this feature important?

I assume that no users will want their scripts to have a step in which the browser goes to an `about:blank` page. It will be just extra work for them to remove it.

Furthermore, IMO this enhancement makes the user more attentive to the URL field as they will have to enter a URL to start recording.

### Additional information

We still need to check whether we really want to implement this "enhancement". I don't think it's a big deal, but it does raise the user's attention to using the initial URL input properly.

**Comment by justinkambic** [comment]
Related to https://github.com/elastic/synthetics-recorder/issues/123.

**Comment by kyungeunni** [comment]
Thanks to the UI enhancement made by #123, it is now more clear that user needs to provide URL before start recording 🎉 

I have no objection making the URL field mandatory but I'd like to hear @hbharding's thought on this issue. 
I guess the way we can achieve this is to disable the `Start` button when the URL input is empty. My only concern is that if we make the Start button disabled, then all the buttons are disabled by the time the app is launched so users might not know what to do.
Here is how it looks right now before clicking the `Start` button:
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/16660866/160668636-7f944836-d49f-4fc8-baea-8e0d7eab105f.png">

Also you mentioned:
> I assume that no users will want their scripts to have a step in which the browser goes to an about:blank page. It will be just extra work for them to remove it.

If a user start recording a journey without an URL, it won't generate `navigate` action with `about:blank` but wait until the user navigate by typing a url in the address bar and generate it. So from user's perspective, it won't make any differences. 
This is what it looks like when recording without an URL and navigating manually in the browser:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/16660866/160667100-d9696974-c4e1-4028-af58-bdcc36be0168.png">

So it is also an option to leave it as it is now.

**Comment by justinkambic** [comment]
Eventually we're going to have a landing page that will contain the URL bar and a start button, so the concern of disabled buttons will be less of an issue at that point.

I also think it's a better experience to have them enter the URL they want into our search field than have them wait for the browser to launch and then type it there, but that's just an opinion. Also curious to hear @hbharding's opinion on the matter.

**Comment by paulb-elastic** [comment]
I know @drewpost was also keen on enforcing this

**Comment by kyungeunni** [comment]
Should we also add URL format validation, it would be misleading if the Start button is enabled as soon as there's an input.

**Comment by paulb-elastic** [comment]
I tend to think that validation on the URL can be fraught with problems in this particular scenario.

For example, on my local network, maybe `a` is valid to put into the browser address bar.  It may resolve (local DNS/proxy server), and be completely fine as a site to test.  However, it’s going to fail typical URL validation.

Because we allow monitors to run on internal networks, I would suggest the only validation (if we are going to make the URL mandatory), is to ensure there’s at least 1 character in the input box.

What do others think?

**Comment by shahzad31** [comment]
POST FF Testing looks god !!

We can't start journey without url 

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/3505601/172369044-ec1cd38e-c5ee-49f0-b05f-c5e4c7082e6e.png">
