### ISSUE TITLE
[Enhancement] Users should not be able to replay steps during test recording

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#127]
### Feature summary

Currently, users can click to replay test's steps _during_ the recording. We should only enable the `replay` feature once users have stopped the recording (or paused it, if we decide to allow that).

### Why is this feature important?

Even though this feature works fine, it's confusing that users could replay steps as they record journeys.

Disabling this feature would make the expected flow clearer.

### Additional information

We still need to discuss whether we'd like to implement this enhancement. We also need to discuss the possibility of only being able to `stop` a recording (removing the `pause`), as that may influence the desired behaviour for this enhancement.

**Comment by justinkambic** [comment]
I think this enhancement makes sense. It doesn't really hurt anything to have the recorder test the script during the session, but I agree it's weird.

**Comment by paulb-elastic** [comment]
Let's review the user flow and UX once https://github.com/elastic/synthetics-recorder/issues/87 is complete
