### ISSUE TITLE
[Enhancement] Expandable step details for script replays

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#128]
### Feature summary

Currently in Figma there's a different layout for test replay results. In it users can also expand steps on the recorder.

Expanding replayed steps is not _currently_ possible.

**Current implementation:**
<img width="540" alt="Screenshot 2021-12-20 at 09 46 40" src="https://user-images.githubusercontent.com/6868147/146747050-f43f651b-015a-461c-992d-690a82b0f716.png">

**Designs:**
![Screenshot 2021-12-20 at 09 43 48](https://user-images.githubusercontent.com/6868147/146747054-a4236633-3c84-457d-b9d1-5ab342ebf11e.png)

### Linked resources

See Figma (won't add link here as that's internal).

### Additional information

Related to: https://github.com/elastic/synthetics-recorder/issues/61

**Comment by liciavale** [comment]
This is part of https://github.com/elastic/synthetics-recorder/issues/131 so we are going to close this issue.
