### ISSUE TITLE
[Enhancement] Implement the new designs for exporting scripts

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/synthetics-recorder#129]
### Feature summary

Currently, exporting scripts opens a dialog to save the journey's code. On the designs, on the other hand, the journey's code appears within a fly-out from which the user can copy the code.

⚠️ For this, we'll keep the "copy to clipboard" icon within the code-block but we'll update the button on the bottom right to handle the "export" functionality.

**Current implementation:**

<img width="1444" alt="Screenshot 2021-12-20 at 09 51 17" src="https://user-images.githubusercontent.com/6868147/146747771-c493cab1-154e-479b-9bd1-7440d7235b0f.png">

**User story:**

As a user of the script recorder

- I need to be able to export the script
- I need to be able to select between inline/suite script before exporting

so that I get the .js that I'll upload to the monitor management flow

### Linked resources

Figma is internal only, so I won't link it here.

### Additional information

@liciavale here I think we also need to check how to allow users to export as a suite, not only as an inline test. I couldn't see how that's done in the designs.

**Comment by liciavale** [comment]
Hey @lucasfcosta I've added the user story to the description of the issue covering the inline/suite script. I'll add the design to cover this shortly.

**Comment by lucasfcosta** [comment]
@liciavale isn't this a duplicate of https://github.com/elastic/synthetics-recorder/issues/121 though?

Shall we close this one? I don't understand the difference between the two.
