### ISSUE TITLE
Replay/Test steps flow

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#131]
As a user of the script recorder

- [x]  I want to test the script I created
- [x] I want to see the steps that are successful/skipped/failed
- [x] When a step is failing I want a summary that helps me to identify what went wrong 

In order to identify any underlying issues/errors, I will need to fix them.

<details>
<summary>Deliverables</summary>

![test](https://user-images.githubusercontent.com/8301088/148277298-5096709e-ae55-4014-8e4b-e809107b242d.gif)

- [Figma file](https://www.figma.com/file/6xfG7uIpgc84d62JnXhOMV/Script-recorder?node-id=696%3A119428) 

- [Prototype ](https://www.figma.com/proto/6xfG7uIpgc84d62JnXhOMV/Script-recorder?node-id=848%3A128541&scaling=scale-down&page-id=696%3A119428&starting-point-node-id=696%3A119429)
</details>

**Comment by lucasfcosta** [comment]
@liciavale I think this issue somewhat overlaps with: https://github.com/elastic/synthetics-recorder/issues/128

Shall we close one of them?

**Comment by liciavale** [comment]
Just a note about this flow:
When users get an error the default status of the error in the side panel should be collapsed, and users will need to expand it manually if they want to.
Wdyt? @justinkambic @lucasfcosta

**Comment by lucasfcosta** [comment]
@liciavale that sounds fine to me, but I think even though the panel is collapsed there should be a clear indication of failure outside of it and something which nods them towards the panel so they know they can/probably should expand it.

**Comment by liciavale** [comment]
@lucasfcosta Yes, with this design they can see that the step failed also when it is collapsed. They can then expand it to see more details.
