### ISSUE TITLE
[Bug] Disallow dirty git status after install

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#134]
### Bug summary

When reviewing https://github.com/elastic/synthetics-recorder/pull/133 I noticed that running `npm install` leaves us with unstaged changes/files. We should aim to avoid this side effect of installing, and check for it after performing an install in CI.

### Recorder Version

build from source

### Steps to reproduce

1. Checkout `main`. 
1. `git status` should show no unstaged files.
1. `npm install`
1. `git status` will now show some unstaged files.

### Expected behavior

`npm install` should still have a clean `git status` run.

**Comment by kyungeunni** [comment]
Is this still happening? When I checked, I couldn't see this behaviour anymore.

**Comment by justinkambic** [comment]
@kyungeunni I think it's likely resolved itself. If I were to guess it was probably an effect of npm 6 or old deps needing upgrading that we have since fixed. I'm fine to close if you can't reproduce the problem anymore.

**Comment by kyungeunni** [comment]
I see! Thanks for confirming, @justinkambic!! I will close it for now.
