### ISSUE TITLE
[Bug] URL should increase when re-sizing the window

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#161]
### Bug summary

When users increase the size of the recorder, The URL should be responsive too

<img width="1562" alt="Screenshot 2022-02-22 at 14 01 29" src="https://user-images.githubusercontent.com/8301088/155313106-c6cc4a24-a196-440f-a136-3d2860f83666.png">

### Steps to reproduce

1. Open the script recorder
2. Increase the size of the window

### Expected behavior

The URL should be responsive

**Comment by emilioalvap** [comment]
Tested on v0.0.1-alpha.3, LGTM
