### ISSUE TITLE
[Enhancement] Update the start over modal copy

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#164]
### Bug summary

<img width="818" alt="Screenshot 2022-02-22 at 14 00 06" src="https://user-images.githubusercontent.com/8301088/155316031-cd415f2f-e30f-4ae5-adce-4a8d72081ff3.png">

### Steps to reproduce

1. Start the recording
2. Record a script
3. Stop the recording 
3. Click on Start over

### Expected behavior
Replace the copy with:

By starting over, the script and all related steps will be permanently deleted. Are you sure you wish to proceed?

Cancel - Start over

**Comment by paulb-elastic** [comment]
@liciavale I am seeing the above warning, is the bug that you are not seeing it?

**Comment by liciavale** [comment]
Hey @paulb-elastic I can see it but I think we should replace the copy, it's just an enhancement not really a bug, I changed the label.

**Comment by shahzad31** [comment]
Start over modal copy is updated !!

POST FF Testing LGTM !!
