### ISSUE TITLE
[Enhancement] Add a tooltip to the suite checkbox 

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#166]
### Feature summary

We should add a tooltip to the suite checkbox - export a script flow

<img width="889" alt="Screenshot 2022-03-01 at 15 18 11" src="https://user-images.githubusercontent.com/8301088/156199687-1f874c90-76f4-4673-a6ca-4d1ae259a2a2.png">

<img width="889" alt="Screenshot 2022-03-01 at 15 41 19" src="https://user-images.githubusercontent.com/8301088/156200032-5fb3ebcf-9d35-4c83-bc31-78f1e15db835.png">

### Why is this feature important?

For users that are not familiar with the suite concept, this can give more context.

**Comment by drewpost** [comment]
Putting on backlog and we'll make sure to do in synthetics app

**Comment by paulb-elastic** [comment]
We will re-review the UI for this in the future (e.g. multi tab for each type of export)
