### ISSUE TITLE
[Chore] Migrate generator code out of `@elastic/synthetics` to recorder

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#185]
### Task summary

The code responsible for generating step/action code today lives in `@elastic/synthetics`. The `synthetics` repo needs to update its Playwright version to resolve user issues, and because we are using a doctored fork of Playwright in the recorder, we will need to diverge for a while. This means we cannot use future releases of `synthetics` for the time being.

~As part of this temporary divergence, we will move the code that currently lives in `synthetics` over to the recorder so we are able to maintain and change it as needed without having to update the `synthetics` dependency version.~

We are going to copy this generator code to the Recorder and modify it as needed for now. We will have to reconcile the version living in Synthetics with our downstream modifications at some point in the future.

### Linked resources

https://github.com/elastic/synthetics/blob/main/src/formatter/javascript.ts

### Additional information

At the end of this change, the types for `Steps`, `Step`, `ActionInContext`, `Action`, should all live in the recorder, as well as the code necessary to generate JavaScript code from the actions users create using the Recorder.

**Comment by shahzad31** [comment]
Discussed with JK 

Doesn't need post FF Testing !!
