### ISSUE TITLE
[Bug] Status indicator for Assertion is missing and unsaved state persists for actions

### ISSUE THREAD

**Issue by kyungeunni** [elastic/synthetics-recorder#201]
### Bug summary

Found a couple of bugs while testing #65

- Unlike other actions, assert action doesn't have a status indicator 

<img width="719" alt="Screenshot 2022-04-13 at 18 35 17" src="https://user-images.githubusercontent.com/16660866/163229558-efecf0ec-5d4e-40b0-9aa9-a375450db1c6.png">

- When editing an action, I could choose to cancel the changes I made. If I go back to edit the action again, the previous state(right before canceling) persists and it is different from the real value stored within the action.
 [![Image from Gyazo](https://i.gyazo.com/969242d76cdd84e90ae1449cafabf5ab.gif)](https://gyazo.com/969242d76cdd84e90ae1449cafabf5ab)

### Recorder Version

0.0.1-alpha.3

### Steps to reproduce

- Record a script, hover on action, and click _Add assertion_ in the control menu. See the status indicator is not visible

- Record a script, hover on action, and click _Edit action_ in the control menu. Change the value in any of the input elements then click _cancel_ button. Click _Edit action_ again for the same action and you will see the unsaved change persists in the input element rather than the actual value shown in the action summary.

### Expected behavior

- Status indicator should be shown to all the actions including `assert` action
- Unsaved changes shouldn't persist when editing actions.

**Comment by justinkambic** [comment]
> Unlike other actions, assert action doesn't have a status indicator

This was actually in the original design, so not a bug.

> I could choose to cancel the changes I made. If I go back to edit the action again, the previous state(right before canceling) persists and it is different from the real value stored within the action.

We can fix this.

**Comment by kyungeunni** [comment]
> This was actually in the original design, so not a bug.

Oh.. why not? I'd be interested to know the reason behind the decision. It would be a bit odd especially if the test fails on the assertion step, and it doesn't have failed indicator on assertion but other actions in the steps do.
