### ISSUE TITLE
[Bug] Action title does not update when values change

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#234]
### Bug summary

*Example:* When updating the URL for a navigate action, for instance, the title doesn't change. We should change the update procedure in the `StepsContext` to recompute the title for the action.

### Recorder Version

alpha-3

### Steps to reproduce

1. Create a `navigate` action.
1. Update its URL
1. Run a test
1. Observe that the outdated URL is what shows up in the test result flyout

### Expected behavior

The title should reflect the latest value for the action.

**Comment by shahzad31** [comment]
Tested for POST FF Testing

It does updates the URL for navigate action now
