### ISSUE TITLE
[Enhancement] Be able to delete actions during the recording

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics-recorder#242]
### Feature summary

As a user of the Script Recorder
I want to be able to delete an action whilst recording
So that I can remove unnecessary browser interactions

ACs:
* I can delete an action even if the recording is in progress, or paused

### Why is this feature important?

When using the script recorder, one can easily click on things by mistake (e.g. identifying a selector), which creates unnecessary _noise_ in the recording.

It’s not currently possible to delete these whilst recording, and although it is possible once the recording is stopped, it can be be difficult to remember which were the unnecessarily captured actions, once finished (i.e. it’s easier to be aware of them when the additional actions are captured rather than at the end).

**Comment by vigneshshanmugam** [comment]
We kind of mutate the PW actions for Assertions as they are not emitted from the Playwright directly instead we generate our own when merging the actions from PW. 

I think we might need to do the same for deletion as you stated here and kind follow the same approach (mark them as delete and skip it from code generation). I don't see any way around it.

**Comment by justinkambic** [comment]
I think we can amend the diffing algorithm to handle deletions as well. I think we will want to invest time in writing unit tests for this feature too because it's going to get pretty complicated.

**Comment by lucasfcosta** [comment]
(oops, accidentally assigned myself to post-FF test this one but I had already tested the original PR)

**Comment by shahzad31** [comment]
POST FF Testing. I can verify that user can delete actions now whilst recording.
