### ISSUE TITLE
Rename `suites` to `projects`

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics-recorder#254]
AC:
* Change `suites` to `projects` (that's the scope of this issue)

![image](https://user-images.githubusercontent.com/131427/169415902-bf1ead5f-cc14-4af3-802a-61d064f816c4.png)

Original issue text below

~We currently let users export javascript for both inline scripts and projects via the UI shown below. The ability to format for projects is confusing to some users. This issue kicks off a discussion on how we can improve this.~

~The more I think about it, the more I think we don't need that feature, for script users they can add their own wrapping `journey statements`, but I want to leave this issue up as a placeholder.~

**Comment by kyungeunni** [comment]
>  script users they can add their own wrapping journey statements

I agree! Although, if it's the very first time the user creates the synthetics code, it's probably not so obvious how they need to organize the test file(including file name). In this case, we can add a help text or a link to the [documentation](https://www.elastic.co/guide/en/observability/current/synthetics-create-test.html) so users know what to do.

If we decide to keep this feature, however, we should:
1. remove the term _suite_ and come up with a better term(probably _project_? but users would need more context what is project).
2. make it obvious what is the difference between these two options.

Also, @shahzad31 suggested a UX improvement around this a few weeks back which I think it's worth while sharing:
>  wonder if we can map the default copy action let's on mac to copy whatever script is recorded , i don't have to click export button
i have seen that kind of user experience in some applications, when you are finish with the steps, it just usually logs a toast and says data is copied to clipboard

**Comment by paulb-elastic** [comment]
To focus on MMFS, change `suites` to `projects` (that's the scope of this issue)

**Comment by shahzad31** [comment]
@paulb-elastic should this be pushed to 8.4?

**Comment by andrewvc** [comment]
I agree with @paulb-elastic and have updated the top comment. All we're going to do here is rename `suites` to `projects`

**Comment by justinkambic** [comment]
Checked this against recent `main` version of recorder, there is no mention of `suite` in copy or code. Post-FF testing LGTM
