### ISSUE TITLE
Testing infrastructure for the recorder

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics-recorder#26]
To be able to release without any friction, we need to come. up with a small amount of Integration/E2E tests that covers the functionality.

### Overall

+ Launch recorder,
+ Start recording session by scripting it via Playwright
+ Able to generate Synthetics code correctly. 
+ Able to run the tests in two modes (inline, suite)
+ Save and export the script. 

Would like to have this as the first level as this brings in much more value than bunch of unit tests that tests the component functionality.

**Comment by lucasfcosta** [comment]
As discussed on Slack, this issue has been broken into:

* https://github.com/elastic/synthetics-recorder/issues/111: We can launch the recorder, control the recording session, and perform assertions on electron (existing PR)
* https://github.com/elastic/synthetics-recorder/issues/112: We can run E2E tests using an existing local web application to generate steps for the script
* https://github.com/elastic/synthetics-recorder/issues/113: We have written tests for the main user journeys within the recorder (we'll then list those inside the issue)

**Comment by lucasfcosta** [comment]
Closing in favour of the three issues above into which this one has been broken down.
