### ISSUE TITLE
Define a process for updating PW for each stack release

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#263]
Over time it will be necessary to upgrade Playwright versions regularly. This will be a result of a continuation of the work we accomplish in https://github.com/elastic/synthetics-recorder/issues/262.

**Comment by kyungeunni** [comment]
We defined updating PW process in [README.md](https://github.com/elastic/synthetics-recorder#managing-playwright-dependency). It is focused on updating the PW version whenever Synthetics agent uses a newer version of PW, so updating PW regularly for each stack release should be in Synthetics agent's responsibility, then the recorder will follow its update. cc @vigneshshanmugam
