### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#264]
Thus far we have been approaching unit testing with the mindset of "don't write tests for anything we think might change". This is primarily related to UI components, but there are a number of untested backend functions and other areas of the project that we should cover before going GA.

It's possible this ticket will eventually become a meta issue for tracking different segments of the codebase. We might also want to improve our automation to provide easy access to metrics on unit test coverage, so we can zero in on areas that are completely untested.

## Todo
- [ ] Add tests to `onTest` electron code https://github.com/elastic/synthetics-recorder/issues/235
- ...

**Comment by kyungeunni** [comment]
Thanks to @justinkambic, Frontend code has very good test coverage, but we don’t have the test coverage we’d like to have on the main process part yet. However, e2e tests complement the lack of unit tests on this part so we will close this for now, and come back to it.
