### ISSUE TITLE
Provide license info with the Script Recorder

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics-recorder#265]
As part of making the Script Recorder GA, we need to declare the licenses of the various components we're using (e.g. in an _About Box_)

**Comment by kyungeunni** [comment]
Had a chat with the team. We will create a txt file declaring the licenses (similar to how [beats](https://github.com/elastic/beats/blob/main/NOTICE.txt) or [synthetics](https://github.com/elastic/synthetics/blob/main/NOTICE.txt) do) and bundle it together, and show it in the _About_ box, either as textarea-like element or acknowledgments button that opens up a window with the license contents in it. 
example of elastic SHIELD: 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/16660866/185438178-66c4fc0c-5fa2-47f0-96b1-37ca29bb46c3.png">

**Comment by justinkambic** [comment]
Post-FF Testing LGTM
