### ISSUE TITLE
[Enhancement] Simplify `uuid` test workaround

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#279]
### Feature summary

In https://github.com/elastic/synthetics-recorder/pull/275 we implemented a workaround solution that will allow our tests to run in newer versions of Jest. It may be possible to simplify what we've done in a follow-up by having jest ignore `uuid` when it is transforming the TS, which would allow us to omit a custom resolver.

### Why is this feature important?

It will simplify the unit testing infrastructure.

### Linked resources

The linked PR includes links, also check out [this PR](https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149) for more info on the problem.

**Comment by kyungeunni** [comment]
If I understood it correctly, all the files under `node_modules` are ignored by transformers as default, meaning `uuid` module should be ignored. The way I see it, it's not the problem of transforming the TS but that `uuid` only provides ESM when we simulate the environment as a browser. More details are described here: https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149

**Comment by justinkambic** [comment]
It sounds like for now we will keep the existing solution, so closing this.
