### ISSUE TITLE
[Bug] Cannot edit fill value on win11 after recording

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics-recorder#282]
### Bug summary

Editing an input fill command is not possible (at least not on my win11 box).

### Recorder Version

1.0.3

### Steps to reproduce

Recorded a journey, visiting google.com and typing some search text in the box. Later, could not edit the fill value in the UI.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/131427/177425967-7a0700c9-7806-4b54-9476-9caa4270644b.png">

**Comment by kyungeunni** [comment]
++ Same on mac
