### ISSUE TITLE
[Bug] Synthetics recorder causes massive slowdown on some sites

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics-recorder#293]
### Bug summary

On some sites the recorder browser runs incredibly slowly, probably due to our custom CSS overlays.

### Steps to reproduce

Go to a slow site (ask andrew for a URL) and try to use the recorder, nothing on the page will work

**Comment by kyungeunni** [comment]
This only happened to a specific website, and it wasn't recorder specific bug since the same slowdown was observed when using playwright recorder too. Now that we've updated PW versions to a recent version, I've tested again and it doesn't seem to happen.
