### ISSUE TITLE
Update the Synthetics/Playwright versions in the Script Recorder

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics-recorder#393]
For the next (1.0) release, we need to update Synthetics and Playwright to a more recent version, more aligned with the 8.8 release

- [ ] Update Playwright and Synthetics ([reference](https://github.com/elastic/synthetics-recorder#managing-playwright-dependency))
- [x] [Review the code generation](https://github.com/elastic/synthetics-recorder/issues/393#issuecomment-1495288960) and bring it up-to-date with the updated version of Playwright

**Comment by kyungeunni** [comment]
I'm adding one more task to review the [code generation part](https://github.com/microsoft/playwright/blob/release-1.31/packages/playwright-core/src/server/recorder/javascript.ts) from the Playwright when updating the new version, as this is copied manually from Playwright's code base and residing in our [codebase](https://github.com/elastic/synthetics-recorder/blob/main/electron/syntheticsGenerator.ts#L151). Seems like our generator is outdated.

**Comment by vigneshshanmugam** [comment]
@kyungeunni Can you do it on the [Synthetics](https://github.com/elastic/synthetics/blob/f5dc2af66f8e0859ba3d89540235682bb930e386/src/formatter/javascript.ts#L75) given we can go back and use it instead of having it here. We copied it here as we wanted to use a custom steps stuff. Now that both are pretty much the same, we can go ahead and have it on single place instead. Thanks.

**Comment by kyungeunni** [comment]
@justinkambic Do you think we can tackle the above point @vigneshshanmugam mentioned as part of updating Playwright version update? I think it's also worth writing it down in the README.md about the codegen as part so we don't forget.

**Comment by justinkambic** [comment]
I think it would be good to follow-up [the existing beta-43 upgrade](https://github.com/elastic/synthetics-recorder/pull/399) with this migration, as that upgrade isn't going smoothly and I'd prefer to limit scope creep.

**Comment by justinkambic** [comment]
I'm re-opening this. We closed the ticket after a code-gen update, but I am going to re-open this as we can now track the migration for the recorder to Synthetics v1 after it is released.

We also might want to keep this open until https://github.com/elastic/synthetics-recorder/issues/407 is resolved as well.

**Comment by justinkambic** [comment]
Ran into some [collateral damage](https://github.com/elastic/synthetics-recorder/pull/412#issuecomment-1542453901) during the implementation of this code gen migration and PW update, we can probably do something upstream to make the fix in the recorder unnecessary. Will be helpful if anyone else tries to leverage this feature of Synthetics as well.
