### ISSUE TITLE
Update to the latest version of Playwright/Chromium and release

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics-recorder#449]
To keep the Recorder up to date, upgrade to the latest version of Playwright/Chromium

**Comment by justinkambic** [comment]
@paulb-elastic it seems that Synthetics is using `1.35.0` version of Playwright, which is the same that the Recorder uses. Is this ticket preemptive of future changes to Synthetics?

**Comment by vigneshshanmugam** [comment]
++ this is a repetitive task that we do for every release. Check synthetics part https://github.com/elastic/synthetics/issues/807

**Comment by justinkambic** [comment]
Aha thanks for clarification @vigneshshanmugam.

**Comment by paulb-elastic** [comment]
@justinkambic did this in https://github.com/elastic/synthetics-recorder/pull/457

**Comment by paulb-elastic** [comment]
Reopening to get the release done

**Comment by paulb-elastic** [comment]
1.2.0 of the recorder published (no longer draft) and DOWNLOAD.MD updated to point to the new version
