### ISSUE TITLE
[Script Recorder] Build macOS Recorder as Universal App

### ISSUE THREAD

**Issue by drewpost** [elastic/synthetics-recorder#52]
We need to natively support Mac users running Intel machines as well as those based on Apple Silicon (M1, M1 Pro, M1 Max). We can do this by either creating a version of the app specifically for Apple Silicon users or creating a universal app that combines both binaries. My preference is to ship a universal app vs having two separate variants.

https://github.com/electron/universal

**Comment by justinkambic** [comment]
> My preference is to ship a universal app vs having two separate variants.

I'd actually rather ship two binaries for a couple of reasons.

#### Extra work

A universal build will require some extra work; we will need multiple versions of the browser deps, and there's a conflict when trying to build a universal "fat" archive:

```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/n_/3ndtv3kn14q7f2n0y104rzk40000gp/T/electron-universal-yM9kEg/Tmp.app/Contents/Resources/local-browsers/chromium-907428/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/94.0.4595.0/Chromium Framework and ~/synthetics-recorder/dist/mac-universal--arm64/Elastic Synthetics Recorder.app/Contents/Resources/local-browsers/chromium-907428/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/94.0.4595.0/Chromium Framework have the same architectures (x86_64) and can't be in the same fat output file
    at ChildProcess.<anonymous> (~/synthetics-recorder/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)
```

#### Larger bin size

A universal binary is going to be around 2x the size. There's no magic, it's basically a wrapper around `x64` and `arm` contents, and the binary will run whichever is appropriate based on where it's running. This probably isn't an issue for most use cases, but in our case the binary will probably be over 1.5 GB.

I think these two reasons make it a compelling case for shipping two binaries.

**Comment by justinkambic** [comment]
We are shipping the recorder as separate `arm64` and `x64` binaries at the moment. The tradeoff for this solution is already explained above, but as we are OK with this currently, I will close this for now. If we want to revisit this and ship a single binary in the future we can re-open the issue.
