### ISSUE TITLE
Update dependencies and create a release

### ISSUE THREAD

**Issue by jasonrhodes** [elastic/synthetics-recorder#532]
We should make sure all dependencies are relatively on up to date versions and publish a new version of this library, if necessary. 

Dependabot PRs: https://github.com/elastic/synthetics-recorder/pulls/app%2Fdependabot

**Comment by jasonrhodes** [comment]
I don't currently have permissions to add labels or assign this or add this to our team's GH project, so I will do those when I have those permissions.

**Comment by vigneshshanmugam** [comment]
@jasonrhodes I am not able to give permission, but let me what you need in terms of labels/assignment etc. I can help here.
