### ISSUE TITLE
[Script Recorder] Assertion

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#65]
As a user, I need to

- [x] add an assertion related to a specific action at any point of my journey
- [x] edit an assertion being able to update the assertion type, selector, and expected value
- [x] delete an assertion

to easily validate an action content of my flow

<details>
<summary>Deliverables</summary>

![43Xhfql1cE](https://user-images.githubusercontent.com/8301088/147131485-99aab0cd-3ee0-45e3-bc61-e322739830dc.gif)

- [Figma](https://www.figma.com/file/6xfG7uIpgc84d62JnXhOMV/Script-recorder?node-id=774%3A128000)
- [Prototype](https://www.figma.com/proto/6xfG7uIpgc84d62JnXhOMV/Script-recorder?node-id=756%3A126651&scaling=scale-down&page-id=683%3A126181&starting-point-node-id=683%3A126878&show-proto-sidebar=1)
</details>

<details>
<summary>User feedback first iteration (archive)</summary>

## Feedback on the initial flow we showed to the users
We received clear feedback about the assertion after users added them.
Some points/considerations were raised during user testings:

- In the current build we call them Assertion 1,2,3... and we show the selector in the tooltip. (see screenshot). Calling them this way doesn't give any value. Let's remove it and show the selector field instead. 

<img width="503" alt="Screenshot 2021-11-02 at 18 02 21" src="https://user-images.githubusercontent.com/8301088/139920608-0b498751-8dff-4b1b-a8f3-7ad1225ebff2.png">

- Having the selector as a tooltip is too hidden, some users would like to see this upfront. We also have to truncate this if this is too long so my proposal is to replace Assertion 1,2,3 with the selector name/type.

<img width="554" alt="Screenshot 2021-11-23 at 11 20 09" src="https://user-images.githubusercontent.com/8301088/143015425-c70ade6f-a028-4333-8cec-73c6347aba9d.png"> 

- Once they added assertion users expect to be able to edit the selector field straight away without opening the side panel again (same functionality of editing the step or action) so I think we should reuse the same pattern we will need to use for editing the step name.
</details>

**Comment by justinkambic** [comment]
Reopening this because Assertion elements are missing the info icon/tooltip.

**Comment by kyungeunni** [comment]
A couple of bugs came up while testing, created a new issue: #201

**Comment by kyungeunni** [comment]
I'm reviewing the design spec and what we have in the recorder and I've seen some differences, and I noticed there is a conceptual discrepancy around Assertion.
 
From what I've seen in the spec, an Assertion belongs to an Action (Assertion is not a type of action). In fact Assertion doesn't have a status indicator and it etc).

But what we have in the Recorder is quite different. Assertion acts as an action: when you open the control of Assertion, you see the same menu as Actions's (you can add an Assertion from an assertion, and you can edit Action)
[![Image from Gyazo](https://i.gyazo.com/b3a448f773e4337ae5cd6dd3e201a5e5.gif)](https://gyazo.com/b3a448f773e4337ae5cd6dd3e201a5e5)

Also you can divide the step right above the assertion so it doesn't have a correlation with the action you've created from.
[![Image from Gyazo](https://i.gyazo.com/890c31b15b5085ee10ea5e8825caf963.gif)](https://gyazo.com/890c31b15b5085ee10ea5e8825caf963)

In my opinion, Assertion acting as a standalone action makes much sense as I don't see the necessity of making assertion the part of action. In fact, when the code is generated, the assertion is just a separated execution not related to any action(We can even change the selector of assertion so it has less connection with the action too.)

So I wanted to confirm that:
1. We treat the assertion as an action. This would mean having status indicators for assertions too.
2. It is ok to say this ticket is marked as done even though it is a bit different from what we have in the recorder.

cc @justinkambic @hbharding

**Comment by justinkambic** [comment]
Assertions are actions (this is a Playwright-level decision), and I think the UI should reflect that.

**Comment by paulb-elastic** [comment]
I also think this is correct, especially as they are nested as part of a step (a step can rightfully have multiple _actions_ and multiple _assertions_, interspersed in any way).  Hiding an assertion _under_ an action makes it harder to see what’s going on, as well as the complexity of having numerous assertions.  I think seeing assertions as _first class_ makes sense.

There is also a valid use case of wanting to move an assertion to a different step, so allowing a new step to be added (above an existing assertion) makes sense to me.

/cc @drewpost

**Comment by justinkambic** [comment]
I've created https://github.com/elastic/synthetics-recorder/issues/222 to address this.
