### ISSUE TITLE
Script recorder onboarding

### ISSUE THREAD

**Issue by liciavale** [elastic/synthetics-recorder#74]
We should improve the script recorder onboarding, from the download (github) to Empty states, Clear steps and help text.

Atm, we don't have a good onboarding for script recorder users. 

Define this experience for:
- First-time usage (empty states/onboarding considering we don't have versions control)
- Everyday usage (help users handle assertions, clear the script, test the script etc)
- Export and upload (give users info regarding how to upload the script and link these experiences)

**Comment by justinkambic** [comment]
This seems like an issue that could take advantage of the [EUI tour](https://elastic.github.io/eui/#/display/tour) feature, we should refine this when we feel we have the necessary time.

**Comment by paulb-elastic** [comment]
Closing for now, we can pick up again in the future with a definition of what we want
