### ISSUE TITLE
View Recorder Input on top of Browser as You Record

### ISSUE THREAD

**Issue by drewpost** [elastic/synthetics-recorder#88]
As a user of the script recorder on a small screen (laptop, smaller desktop external), I find myself really wanting positive or negative feedback of "did that click I just did record, did that text I just typed come through etc" and was the recorded action what I expected it to be.

Suggested implementation: It would be great to have some sort of always on top mini window showing the most recent steps as you're doing them on screen for that positive affirmation for the user. It would also be great to have a quick "delete" option for each recorded setp in case I fat finger something and need to remove it without needing to start from scratch again.

**Comment by paulb-elastic** [comment]
Need further discussions with Engineers to understand different approaches and complexities

**Comment by paulb-elastic** [comment]
Pushing to post 1.0
