### ISSUE TITLE
Ability to start reordering from within an existing series of steps

### ISSUE THREAD

**Issue by drewpost** [elastic/synthetics-recorder#89]
As a user of the script recorder with a script that's already been recorded, I want the ability to start re-cording from a point in the test of my choosing so that I don't have to re-record the whole thing if only a small part has changed.

For example, let's say I have a 4 step journey that looks like this:

1. Homepage
2. Search page
3. Product page
4. Checkout flow

We then do a code change on the product pages so that I need to re-record that step. I'd want to be able to start recording from after step 2 and then stop recording and replace the existing step 3 and leave step 4 as it was before.

**Comment by justinkambic** [comment]
I'm closing this for now as we haven't had any movement on it and there are major architectural changes needed for it to be possible. We can reopen it when we decide to work on it.
