### ISSUE TITLE
feat: update play/pause/stop functionality per new design

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics-recorder#96]
Related to https://github.com/elastic/synthetics-recorder/issues/70.

Per designs in the linked meta issue, we should implement a new flow for play/pause/stop in the recorder's flow.

- [x] Start button will now become Pause during a run
- [x] No Stop button, stop button is now "start over", which will re-launch a new session.
  - for now, this will kill the existing chromium process, and focus on the URL input. Eventually we will have a "start" page that consists of just the URL input and a start button.

More info/design on the parent issue.

**Comment by justinkambic** [comment]
I think it'll be better to update this functionality first and then treat the addition of a startup screen as an isolated change.

[I also think](https://github.com/elastic/synthetics-recorder/issues/70#issuecomment-983758099) it might be better if, once they're past the start screen, we don't return them there when they start over. That's just my opinion of course.

**Comment by awahab07** [comment]
**Post FF Testing**

LGTM
"Start recording" button becomes "Pause" during a recording session. 
There's no "Stop" button, rather during a recording session, there's a "Start over" button.
Before starting over, "Start over" button confirms from the user to delete all recorded steps and start over.

https://user-images.githubusercontent.com/2748376/148784815-806dc195-9ad2-464d-926a-8ff0bf4de1fc.mov
